# Generated by Django 5.2.3 on 2025-06-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('workforce_size', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'd_company',
            },
        ),
        migrations.CreateModel(
            name='DCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('monnaie_iso3', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'd_country',
            },
        ),
        migrations.CreateModel(
            name='DDate',
            fields=[
                ('date_key', models.DateField(primary_key=True, serialize=False)),
                ('day', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('quarter', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
                ('day_week', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'd_date',
            },
        ),
        migrations.CreateModel(
            name='DSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_group', models.CharField(max_length=100)),
                ('tech_label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'd_skill',
            },
        ),
        migrations.CreateModel(
            name='DSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'd_source',
            },
        ),
    ]
