# Generated by Django 5.2.3 on 2025-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('salary_min', models.FloatField()),
                ('salary_max', models.FloatField()),
                ('skills_extracted_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DCompany',
        ),
        migrations.DeleteModel(
            name='DCountry',
        ),
        migrations.DeleteModel(
            name='DDate',
        ),
        migrations.DeleteModel(
            name='DSkill',
        ),
        migrations.DeleteModel(
            name='DSource',
        ),
    ]
