# Generated by Django 5.2.3 on 2025-07-04 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0002_joboffer_delete_dcompany_delete_dcountry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='skills_extracted_list',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='sector',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
