# Generated by Django 5.2.3 on 2025-07-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0003_remove_joboffer_country_remove_joboffer_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
